services:
  - type: web
    name: vote-cast
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vote_cast.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vote_cast.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-subdomain.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: vote-cast-db
          property: connectionString

databases:
  - name: vote-cast-db
    plan: free
