services:
  - type: web
    name: iovote
    env: python
    plan: free
    startCommand: |
      python manage.py migrate --noinput && \
      python manage.py collectstatic --noinput && \
      gunicorn iovote.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: iovote.settings
      - key: DATABASE_URL
        fromDatabase:
          name: vote_cast_db  
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: postvezha@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
    autoDeploy: true

databases:
  - name: vote_cast_db  
    plan: free
