# Generated by Django 5.1.7 on 2025-04-18 19:34

import datetime
import django.db.models.deletion
import uuid
import voting_sessions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('session_start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session_end_time', models.DateTimeField(blank=True, db_index=True, default=voting_sessions.models.calculate_default_end_time, null=True)),
                ('choice_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True)),
                ('voting_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True)),
                ('description', models.TextField(blank=True, default='Default description', null=True)),
                ('email_sent', models.BooleanField(db_index=True, default=False)),
                ('creator_email', models.EmailField(blank=True, default='admin@example.com', max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting_sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='sessions', through='voting_sessions.SessionUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_start_time'], name='voting_sess_session_2978f6_idx'),
        ),
    ]
