# Generated by Django 5.1.5 on 2025-02-18 20:06

import django.db.models.deletion
import voting_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('session_start_time', models.DateTimeField(blank=True, null=True)),
                ('session_end_time', models.DateTimeField(blank=True, default=voting_sessions.models.calculate_default_end_time, null=True)),
                ('choice_duration', models.DurationField(blank=True, null=True)),
                ('voting_duration', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='Default description', null=True)),
                ('creator_email', models.EmailField(blank=True, default='default@example.com', max_length=255, null=True)),
                ('invitation_endpoint', models.URLField(blank=True, default='http://example.com/invite', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting_sessions.session')),
            ],
        ),
    ]
