# Generated by Django 5.1.5 on 2025-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='choice_duration',
            field=models.DurationField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='voting_duration',
            field=models.DurationField(blank=True, default=1, null=True),
        ),
    ]
