# Generated by Django 5.1.7 on 2025-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creator_email',
            field=models.EmailField(blank=True, default='postvezha@gmail.com', max_length=255, null=True),
        ),
    ]
