# Generated by Django 5.1.3 on 2024-11-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='choice_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='voting_duration',
            field=models.DurationField(),
        ),
    ]
