# Generated by Django 5.1.7 on 2025-04-19 20:36

from django.db import migrations

def delete_default_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(email='admin@example.com').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0002_alter_session_creator_email'),  # Replace with actual previous migration
    ]

    operations = [
        migrations.RunPython(delete_default_admin),
    ]
