# Generated by Django 5.2.1 on 2025-06-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0003_remove_default_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='choice_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=60), null=True),
        ),
    ]
