# Generated by Django 5.1.6 on 2025-03-03 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0003_alter_session_invitation_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='choice_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='creator_email',
            field=models.EmailField(blank=True, default='sessioncreator@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='voting_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
    ]
