# Generated by Django 5.1.5 on 2025-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0004_alter_session_choice_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creator_email',
            field=models.EmailField(blank=True, default='postvezha@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='invitation_endpoint',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
