# Generated by Django 5.1.3 on 2024-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0004_session_creator_email_session_invitation_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creator_email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='invitation_endpoint',
            field=models.URLField(blank=True, default='http://example.com/invite', max_length=500, null=True),
        ),
    ]

