# Generated by Django 5.1.5 on 2025-02-06 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0005_alter_session_creator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 20, 49, 13, 973496, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
