# Generated by Django 5.1.5 on 2025-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0005_alter_session_creator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creator_email',
            field=models.EmailField(blank=True, default='admin@example.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='invitation_endpoint',
            field=models.URLField(blank=True, default='https://example.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
