# Generated by Django 5.1.5 on 2025-03-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0008_remove_session_invitation_endpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
