# Generated by Django 5.1.7 on 2025-03-22 19:48

import django.db.models.deletion
import voting_sessions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0009_session_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_end_time',
            field=models.DateTimeField(blank=True, db_index=True, default=voting_sessions.models.calculate_default_end_time, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='sessions', through='voting_sessions.SessionUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_start_time', 'email_sent'], name='voting_sess_session_029402_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionuser',
            unique_together={('session', 'user')},
        ),
    ]
