# Generated by Django 5.1.7 on 2025-03-22 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_sessions', '0010_alter_session_email_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='voting_sess_session_029402_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_start_time'], name='voting_sess_session_2978f6_idx'),
        ),
    ]
