# Generated by Django 5.0.7 on 2024-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingoption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
