# Generated by Django 5.0.7 on 2024-10-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_votingoption_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryOption',
        ),
    ]
