# Generated by Django 5.0.7 on 2024-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_votingsession_voting_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='open_votes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='voting_preference',
            field=models.CharField(choices=[('open', 'Open voting'), ('closed', 'Closed voting')], default='closed', max_length=6),
        ),
    ]
