# Generated by Django 5.0.7 on 2024-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_votingsession_is_active_alter_votingsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
