# Generated by Django 5.0.7 on 2024-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
