# Generated by Django 5.0.7 on 2024-10-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_alter_votingsession_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='open_votes_count',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='votingsession',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days')], default=30),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='voting_preference',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10),
        ),
    ]
