# Generated by Django 5.0.7 on 2024-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_remove_votingsession_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='is_started',
            field=models.BooleanField(default=True),
        ),
    ]
