# Generated by Django 5.2.1 on 2025-06-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
        ('voting_sessions', '0004_alter_session_choice_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_sessions.option'),
        ),
    ]
