# Generated by Django 5.1.5 on 2025-02-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
        ('voting_sessions', '0005_alter_session_creator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting_sessions.session'),
        ),
    ]
